// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: ctx
func (_m *Controller) CreateRecord(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetHistory provides a mock function with given fields: ctx
func (_m *Controller) GetHistory(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetLatest provides a mock function with given fields: ctx
func (_m *Controller) GetLatest(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewController interface {
	mock.TestingT
	Cleanup(func())
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewController(t mockConstructorTestingTNewController) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
